### ISSUE TITLE
[feature request] Add support for PR labels

### ISSUE THREAD

**Issue by srm09** [telia-oss/github-pr-resource#104]
Filtering the PRs based on added labels is a very useful functionality, since we want to setup automatic verification and merge of PRs raised by certain bot accounts.
Is this feature prioritized on the roadmap?

**Comment by itsdalmo** [comment]
Hi @srm09! 
Label filters is not something I have looked at myself, but I'd be happy to review a PR to implement it 😄

**Comment by srm09** [comment]
@itsdalmo I will try to add the feature in a PR and send it over. Thanks!
