### ISSUE TITLE
Feature request: configurable git depth

### ISSUE THREAD

**Issue by gabro** [telia-oss/github-pr-resource#106]
In the README it's said that `git.*` parameters from https://github.com/jtarchie/github-pullrequest-resource did not make into this resource.

My team would like to migrate to this resource for a project that uses `git.depth: 1` to gain some speed when cloning a sizeable repository.

Is there a design reason why that specific parameter didn't make it and - if not - would you accept a PR adding it?

Thanks

**Comment by itsdalmo** [comment]
No specific reason that it was not added to the resource no, would be thankful for a PR to add it 😄 What do you think about having it as a `get` parameter rather than in the `source` configuration?

**Comment by gabro** [comment]
Thanks for the feedback. I'll work on this as soon as I have a minute.

> What do you think about having it as a `get` parameter rather than in the `source` configuration?

@itsdalmo it was this way in the other resource, so 👍

**Comment by itsdalmo** [comment]
Will become available under the `dev` tag since merging the PR. Let me know if it works and we can put together the release 👍

**Comment by gabro** [comment]
I'll give it a try soon!

**Comment by itsdalmo** [comment]
Found two issues that have been fixed in #114. `dev` is being rebuilt as we speak 😅
