### ISSUE TITLE
[feature request] Disable integration tool and pure check out

### ISSUE THREAD

**Issue by darwin67** [telia-oss/github-pr-resource#115]
It would be great if `integration_tool` can also be `none` besides the current `merge` and `rebase`.

The more activity on a repo, the higher the possibility that it will create merge conflicts and it's not ideal that builds or tests fails even though it's still work in progress and just because someone merge something else in.

Also, I would prefer that this resource has the option to just pull down the repo and checkout the branch rather than trying to do some extra stuff like merging and rebasing with it.

**Comment by darwin67** [comment]
And this is exactly what I'm talking about.

It's not ideal to just fail at the resource retrieval phrase because it try to do something smart.

![merge-conflict](https://user-images.githubusercontent.com/5746693/58992253-20b82680-879f-11e9-8bab-9d22c70640b2.png)

**Comment by itsdalmo** [comment]
Hi @darwin67 and thanks for the feature request!

Initially we wanted to be opinionated and try to limit the number of flags on the resource (so it's easier to use). But seeing as we have added an `integration_tool` flag, I'd be happy to review a PR to add e.g. `integration_tool: none` for instance.

**Comment by darwin67** [comment]
Glad to hear that you're open to a PR.
I'll try to submit a PR in the coming days.
