### ISSUE TITLE
Trigger build when `[skip ci]` from PR title

### ISSUE THREAD

**Issue by beeender** [telia-oss/github-pr-resource#124]
when `disable_ci_skip = false` and the PR title contains `[skip ci]` the build will be skipped.
However, after the `[skip ci]` removed, the build won't be triggered either.

Is it the expected behaviour? Is there any way the build can be triggered without push a new commit?

**Comment by itsdalmo** [comment]
Hi and thank you for the issue!

> when disable_ci_skip = false and the PR title contains [skip ci] the build will be skipped.

That is expected behavior yes :D

> However, after the [skip ci] removed, the build won't be triggered either.

Did you remove `[skip ci]` from both commit message of the commit you would like to build, and the title of the PR itself? And are you certain that a new `check` was triggered after doing so?

**Comment by beeender** [comment]
Oh, sorry, the post was not clear enough.

- By making a new commit and remove the `[skip ci]` from the commit message, the build can be triggered.

- If there is **no `[skip ci]` in the commit message**, but only in the PR header, by removing the text from PR header, the build is not triggered. This is my problem.

**Comment by itsdalmo** [comment]
Hi @beeender and sorry for a very long wait. Has this issue resolved itself or are you still having trouble? Have you tried doing as you describe in your 2nd example above, and running `fly check-resource` afterwards to make sure that the `check` is actually being run?

**Comment by itsdalmo** [comment]
Assuming this has been resolved 😄
