### ISSUE TITLE
Retrigger all PRs when master is updated

### ISSUE THREAD

**Issue by dnd** [telia-oss/github-pr-resource#134]
Is there a way to trigger all PRs to be rerun when master is updated? In an effort to ensure continuing compatibility of code, whenever something is merged into master I want to have all PRs run their checks again to ensure they're still in a good state. 

Is this supported by this resource? Maybe I have something configured wrong, but it doesn't appear to be happening for me. If it's not supported, are there any plans for this, or recommendations to accomplish it?

**Comment by itsdalmo** [comment]
Hi, thanks for the issue! There are currently no plans to support this, and I don't think this should be the responsibility of this resource. Have you tried enabling branch protection on and enabling the "Require branches to be up to date before merging"-option?

**Comment by itsdalmo** [comment]
I will close this issue since it has gone quiet :)
