### ISSUE TITLE
Possibility to consume PR payload from git 

### ISSUE THREAD

**Issue by bhutkovskyysos** [telia-oss/github-pr-resource#140]
This resource has many features but every use case is different and I think this is why previous PR resource got deprecated as it is hard to keep up with all features and eventually it becomes very exhausting to accommodate everyone. 

In this case logic lives inside the resource. I think it would be nice to have a freedom of receiving the payload (could be optional setting) and do some logic ourselves to suit the particular use cases. You can get a lot from the payload and no additional overhead has to exist on concourse or resource. Is it possible to retrieve the payload from git? If so, this would help a lot to implement our own logic inside the task to cover various edge cases.

**Comment by itsdalmo** [comment]
This makes a lot of sense, I agree. We could maybe look into having optional data which is written to disk on `get` and separating some of the filtering functionality out into a separate task step (and users could make whatever filtering they wanted in a custom task).

However, I've been a bit hesitant to make big changes to the resource until we know for sure where Concourse will go with resources v2 and what implications that will have for resources and tasks 🤷‍♂

**Comment by itsdalmo** [comment]
Rereading this issue I'm not sure I fully understood what you want to do here. What payload is it you want to receive, and where do you want to implement your custom logic? Also you are aware of the JSON files that are written to disk on [get](https://github.com/telia-oss/github-pr-resource#get)?

**Comment by itsdalmo** [comment]
Closing because the issue is stale :)
