### ISSUE TITLE
Not every commit is picked up by PR resource

### ISSUE THREAD

**Issue by bhutkovskyysos** [telia-oss/github-pr-resource#144]
My pipeline is using PR resource and I noticed so far that not every commit is picked up to trigger it. I have my resource set to `check_every: 10s`, but if there are multiple commits in that time period it will only pick up the latest one. Is this intended behavior? Since the resource itself is not picking up all the commits `version: every` doesn't give a lot of value to my job.

**Comment by itsdalmo** [comment]
Hi @bhutkovskyysos, and sorry for the late response. What you describe is the intended behaviour, i.e. the resource will only produce a new version for the latest commit _per_ open PR. The "per open PR" is where `version: every` comes in and ensures that if a `check` returns the latest commit from 2 or more open pull requests, it will trigger a build for all of them, and not just the most recently updated pull request.

This is unfortunately how the resource will have to work until Concourse supports "spaces" or some similar way of tracking multiple commits in multiple PRs.

**Comment by phillbaker** [comment]
@itsdalmo just curious if you think this resource will address the issue described in https://github.com/concourse/concourse/issues/736, where `version: every` will skip versions if a parallel upstream job's latest build finishes before an older one?

**Comment by itsdalmo** [comment]
@phillbaker the issue you linked seems to affect any resource in Concourse, as long as `passed:` is used in combination with `version: every`. I.e., `github-pr-resource` will be affected as well.

**Comment by itsdalmo** [comment]
I will close this issue as the original question has been answered and it has gone stale :)
