### ISSUE TITLE
Migration: cannot use build variables like `$BUILD_JOB_NAME`

### ISSUE THREAD

**Issue by hstenzel** [telia-oss/github-pr-resource#146]
When migrating from `jtarchie/pr`, I have pipelines that have `context: $BUILD_JOB_NAME`. It would be nice to support that syntax, but if that's not possible there should be a note added to migration.

Thanks!

**Comment by itsdalmo** [comment]
Thanks for the issue. For the record this should just require a small fix here:
https://github.com/telia-oss/github-pr-resource/blob/master/out.go#L41

**Comment by itsdalmo** [comment]
This has been added in #105 and available since `v0.14.0` onwards. It's also refined in #173 which will be a part of the next release 👍
