### ISSUE TITLE
Ability to read the PR description from a file

### ISSUE THREAD

**Issue by RNag** [telia-oss/github-pr-resource#149]
https://github.com/telia-oss/github-pr-resource#put

In the `description` parameter above, I tried having a concourse task that writes to an output file, but when I pass the filename to the parameter, it just outputs the name as a string in the PR description.

It would be nice to support a paramter like `description_file` that will read contents from a file and set the PR description accordingly - please let me know the thoughts on this.

thanks.

**Comment by RNag** [comment]
Update: I created a pull request for this change, please review it when you have time ^^

I am still learning with `go`, so I might have made some beginner mistake - please let me know. thanks.

https://github.com/telia-oss/github-pr-resource/pull/152

**Comment by RNag** [comment]
Hi @itsdalmo , would kindly appreciate a response about this feature...

I think it's a very minor addition to the `pr-resource` (doesn't touch any existing logic) and we are excited to see this minor feature be supported in the current resource.. please let me know any thoughts on this.

Thanks.

**Comment by itsdalmo** [comment]
Hi @RNag - I think the feature request and implementation makes sense/looks good. I'll give it a review later today and/or merge your PR. Sorry I've been slow to respond.

**Comment by RNag** [comment]
no problem.. thank you for reviewing! I think this issue can be closed now as its feature got added 😄 😄
