### ISSUE TITLE
Repo cloning error

### ISSUE THREAD

**Issue by tjb-wiley** [telia-oss/github-pr-resource#157]
I've been working on refactoring my Concourse pipeline, and at some point in the process the `get` step to clone the repo started failing with this:

```sh
Initialized empty Git repository in /tmp/build/get/.git/
Switched to a new branch 'master'
2019/10/20 20:50:14 get failed: clone failed: exit status 1
```
Everything I've tried to this point hasn't fixed the problem, including reverting the pipeline config and going back to the last known working version.

I came across [issue-65](https://github.com/telia-oss/github-pr-resource/issues/65), which lead me to hijacking the container where it's failing and manually clone the repo with:
```sh
git pull https://x-oauth-basic:<ACCESS_TOKEN>@<URI>.git master
```
The above worked just fine.

Per that issue, I also attempted to set the `skip_ssl_verification` flag to `true`, but that didn't help either.

I'm at a loss at why this is failing. The fact that even reverting to the last working version of the pipeline config fails in the same way seems to suggest that it could be an auth issue, but the fact that I can hijack the container and successfully run the command that the resource would run shows that's it's not an issue with the access token. 

Any suggestions? Any help is much appreciated! 

Thanks,
Tim

**Comment by eedwards-sk** [comment]
In an effort to get the failure to reproduce, can you try submitting a json payload to the binary when hijacking?

**Comment by tjb-wiley** [comment]
You mean to the `/opt/resource/in` binary? what should be in the payload? does it need to be all the fields specified here:
https://github.com/telia-oss/github-pr-resource/blob/master/in.go#L66

**Comment by tjb-wiley** [comment]
Closing, this was human error: somehow I managed to add a trailing space to the github token in the `fly set-pipeline` command that I couldn't see. Sorry for the noise.
