### ISSUE TITLE
Can I create a new PR via this resource?

### ISSUE THREAD

**Issue by williammartin** [telia-oss/github-pr-resource#166]
In the README it seems `put` requires an equivalent `get`. I would like to create a new PR, is this something that is supported?

**Comment by itsdalmo** [comment]
Hi @williammartin! Unfortunately his resource only lets you add comments and set statuses on pull request commits, not create the pull requests themselves. Sorry for the confusion!

**Comment by yelizariev** [comment]
Can be closed?

**Comment by williammartin** [comment]
Yes thank you.
