### ISSUE TITLE
Add PR Body to metadata

### ISSUE THREAD

**Issue by RNag** [telia-oss/github-pr-resource#168]
I was curious if it is possible we can include the PR body in the git metadata (or at least allow a toggle-able option in the `get` step that will enable this 🤔 ). The only reason our team needs this is because we want to perform a few validations on the contents of the PR body on each commit.

This is the PR I created for it:
https://github.com/telia-oss/github-pr-resource/pull/167

FYI, I'm not blocked at the moment, since I have temporarily built a docker image from the `master` along with these new changes.

Thanks!

**Comment by itsdalmo** [comment]
Thanks for the issue and PR @RNag! I think this is an interesting use case, but I'm starting to think that every small (and useful) addition we make, unfortunately also makes this resource a bit more bloated and hard to use for everyone else. As such I'd like to hold off on merging any new functionality until we have a good pattern for doing so; e.g. we need to make it opt-in and ensure that we are not increasing the cost (ref #156) for regular use of the resource.

**Comment by RNag** [comment]
Oh ok -  no problem 👍 

Would it be helpful like I mentioned if we made it opt-in in the `get` step itself? e.g. we can introduce some flag like `add_body_metadata` and default it to false, so that nothing changes until someone goes in and enables it.

**Comment by itsdalmo** [comment]
Hi there! Just added my thoughts here:
https://github.com/telia-oss/github-pr-resource/pull/167#issuecomment-563133432

In short, I think that for most people (myself included) there would be more drawbacks then benefits from adding this feature. Also, although this is called a "PR" resource the main responsibility of the resource is to track and set statuses on commits; adding the PR body to the metadata for each commit feels a bit off in that case.

Thanks a lot for the suggestion and the pull request though 🙌

**Comment by RNag** [comment]
sure, no problem 🙂
