### ISSUE TITLE
Add PR Title to metadata

### ISSUE THREAD

**Issue by mjdouble** [telia-oss/github-pr-resource#174]
Currently the metadata includes the top commit message. However, when numerous commits are merged in the same PR, the title is a much more useful piece of metadata. I would like to use ticket IDs from a PR title that could the be passed as metadata to other resources such as a jira-resourse that could then transition a ticket. I have submitted #172 to handle this.

**Comment by mjdouble** [comment]
Is there anything I need to do further to get a review of this PR?

**Comment by itsdalmo** [comment]
Closed after merging #172 - please check out the `dev` image while I put together a release. Also, sorry for the long wait on this (and many other) issue.
