### ISSUE TITLE
not able to use command "git describe" on this resource.

### ISSUE THREAD

**Issue by niharbabu99** [telia-oss/github-pr-resource#184]
In our build script, we use git describe to fetch the commit id.  I have intercepted the pipeline and went to resource folder and tried running the command "git describe" and I get a message "fatal: No names found, cannot describe anything".

But in my local VM where I cloned the repo, I am able to run the command without any issues.  Why am I not able to run the command?
Inside the container : 
![image](https://user-images.githubusercontent.com/42992083/72255474-d51b0480-362c-11ea-9ddd-62dd7dd64c56.png)

Inside My vm:
![image](https://user-images.githubusercontent.com/42992083/72255541-01cf1c00-362d-11ea-89da-e089f9c64932.png)

**Comment by itsdalmo** [comment]
This issue is being discussed in #136, please use that issue instead 👍
