### ISSUE TITLE
Add this resource to the resource-types website?

### ISSUE THREAD

**Issue by taylorsilva** [telia-oss/github-pr-resource#188]
Wondering if you all were thinking about adding this resource to the [resource-types website]? I really like this resource for automating PR workflows and think it would be a good addition to the site. wdyt?

How to contribute: https://github.com/concourse/resource-types/blob/master/README.md

[resource-types website]: https://resource-types.concourse-ci.org/

**Comment by itsdalmo** [comment]
Hey @taylorsilva! I'll look at this first thing when I'm back from vacation, thanks for pointing it out 🙌

**Comment by itsdalmo** [comment]
I've added a PR here: https://github.com/concourse/resource-types/pull/33 - will close this issue once it's merged 👍

**Comment by taylorsilva** [comment]
Looks like it's been merged. The recent github API issues seems to have broken the status of the PR. I can see this resource on the resource-types website now 😄
