### ISSUE TITLE
Resource Checks Failing on Unmarshalling

### ISSUE THREAD

**Issue by rorymalcolm** [telia-oss/github-pr-resource#229]
On `dev` we are seeing resource checks failing across all PR resources with this error:

Looks related to this maybe? https://github.com/telia-oss/github-pr-resource/pull/219

```
run check step: run check step: check: json: cannot unmarshal number into Go value of type string

when parsing resource response:

[{"pr":"880","commit":"294d68f49a8a5f19776e6fabd168d62af721f899","committed":"2020-10-20T03:12:58Z","approved_review_count":0}]
```

**Comment by isaacsanders** [comment]
Yup! Working on it. Thanks for the report.

**Comment by isaacsanders** [comment]
@rorymalcolm Is this looking better for you?
