### ISSUE TITLE
Support for git options

### ISSUE THREAD

**Issue by killermoehre** [telia-oss/github-pr-resource#280]
Hi,

right now I work with a quite big branch with many changes and need to increase `merge.renamelimit`.

```text
warning: you may want to set your merge.renamelimit variable to at least 2069 and retry the command.
```

Any way to configure this in the github-pr-resource?

https://github.com/concourse/git-resource has `git_config` for this.

**Comment by bgandon** [comment]
Unfortunately, there is no hope that you get any support here (#246 was 2+y ago).

But recent news is that the Cloud Foundry community is now maintaining a fork of this resource at [cloudfoundry-community/github-pr-resource](https://github.com/cloudfoundry-community/github-pr-resource).

On our Concourse installation at Gstack, that one is working fine. Could you give a try and submit a PR there?

_(the new resource is a drop-in replacement; you only have to switch `telia-oss`to `cfcommunity` in in the `resource_types:` declaration, i.e. specify `repository: cfcommunity/github-pr-resource`)_

**Comment by killermoehre** [comment]
Can be closed as not my problem anymore. Changed customers.
