### ISSUE TITLE
Check only recent PRs to reduce API limits

### ISSUE THREAD

**Issue by sirmspencer** [telia-oss/github-pr-resource#292]
We have 3 pipelines using this, and we are already hitting git API limits.  Related to [this](https://github.com/telia-oss/github-pr-resource/issues/233) I think.

In that issue it sounds like its from too large of a payload.  We would only need to poll changes from the last few minutes if concourse is running every 2 minutes.

**Comment by bgandon** [comment]
Unfortunately, there is no hope that you get any support here (#246 was 2+y ago).

But recent news is that the Cloud Foundry community is now maintaining a fork of this resource at [cloudfoundry-community/github-pr-resource](https://github.com/cloudfoundry-community/github-pr-resource).

On our Concourse installation at Gstack, that one is working fine. Could you give a try and provide feedback there?

_(the new resource is a drop-in replacement; you only have to switch `telia-oss`to `cfcommunity` in in the `resource_types:` declaration, i.e. specify `repository: cfcommunity/github-pr-resource`)_

**Comment by sirmspencer** [comment]
Thanks for replying.  We just moved to github cloud to support triggers from github instead.
