### ISSUE TITLE
Gathering the name of the branch a pull-request was created on

### ISSUE THREAD

**Issue by larssb** [telia-oss/github-pr-resource#54]
I've read the documentation again on this resource and searched through the issues (also closed ones). I have not been able to find a way to get the branch-name metadata.

Is this possible? If so, how would I do that?

The reason that I want branch-name is to use it as output to a later step in the Concourse-CI pipeline. A step that needs to deploy to either test or production. Based on the branch on which a pull-request was made. E.g.
- `develop`: a pull-request to this branch would be deployed to `test`
- `master`: .... would go to `production`

I think the above method of distinguishing between infrastructure environments is a standard approach.

E.g. for Google Cloud build triggers this is a standard. Documentation on that [here](https://cloud.google.com/cloud-build/docs/running-builds/automate-builds).

However, maybe one should use `tags` when committing. But that also needs to be given as an output and this resource then needs to be able to fetch that.

Thank you.

**Comment by itsdalmo** [comment]
You are right, the name of the base for the PR is not output anywhere and probably should be - I'll make a PR to fix it and get a `dev` image deployed for you to try out! Thanks for submitting the issue 👍

**Comment by larssb** [comment]
Man. Nice @itsdalmo ... thank you. Looking forward to that pull-request.

Have a great evening.

**Comment by itsdalmo** [comment]
PR merged, which should trigger a build of the `dev` tag on DockerHub. The `base_name` and `head_name` in `metadata.json` should have you covered 👍 Let me know if it works out for you!

**Comment by larssb** [comment]
Thank you very much. It works @itsdalmo ... actually I ended up not using it though. As I was mistaking on the flow of the pipeline I was setting up. Mistakenly deploying a release on a pull-request. Where, this shouldn't happen before the PR has been reviewed. So the release deploy should not happen before a push to either the develop or the master branch.
However, I still think having the branch-name is nice if different situations. Makes it possible for one to act and do 'x' if on a certain branch and 'y' if on another.

Again thank you very much.

**Comment by itsdalmo** [comment]
No problem! Still useful to have the branch names in the metadata - I'll go ahead and close this issue now and release the metadata changes at my own leisure then 👍
