### ISSUE TITLE
Link to schema docs incorrect for PR object

### ISSUE THREAD

**Issue by timrchavez** [telia-oss/github-pr-resource#56]
https://github.com/telia-oss/github-pr-resource/blob/627340b1eeb5e3f3f3f56e8bd9cdfd0cb993d3d2/models.go#L77

I think it should be https://developer.github.com/v4/object/pullrequest/ ?

**Comment by itsdalmo** [comment]
Right you are! Thanks for the issue, I'll try to get this sorted ASAP👍
