### ISSUE TITLE
Fire when any file under a directory changes

### ISSUE THREAD

**Issue by hythloday** [telia-oss/github-pr-resource#61]
Hi there! We're using this plugin, which we really like, and running a monorepo, so we have several modules under a single root:

* a
    * src
         * main
             * scala
* b
    * src
        * main
            * scala
* c
    * src
        * main
            * scala

etc. We'd like to trigger separate processes whenever _any_ file under a, or b, or c changes. Our directory trees could be 12 or so levels deep (not one of the things I like about the JVM but it is what it is) and setting our paths as

* `a/*`
* `a/*/*`
* ...
* `a/*/*/*/*/*/*/*/*/*/*/*/*`

gets boring quite quickly. :) I looked in the globbing library you're using and it looks like it should support `a/**` but that didn't work for me. Do you have any suggestions to make this easier to accomplish?

**Comment by itsdalmo** [comment]
Hey! The default built-in globbing in Golang does not support `**`, but fortunately we already have a resolution to this problem thanks to @benweissmann who submitted https://github.com/telia-oss/github-pr-resource/pull/59 which I think does exactly what you want 🎉 

It's currently available under the `dev` tag here:
https://hub.docker.com/r/teliaoss/github-pr-resource/tags/

Would be great if you could try it out and report back 👍

**Comment by hythloday** [comment]
This worked great, thanks so much - deeply appreciate the fast response. 💯
