### ISSUE TITLE
GitHub enterprise repo cloning errors

### ISSUE THREAD

**Issue by marknet15** [telia-oss/github-pr-resource#65]
Hi,

First off, great work with this resource, it looks perfect for my organization's needs.

I was however wondering if you could give me a hand with some issues I have been having around the cloning the repo from GitHub enterprise stage ?

I've found that the "check" resource works perfectly triggering on new PR's however the "get" resource then fails on the "git pull" command:
```
Initialized empty Git repository in /tmp/build/get/.git/
Switched to a new branch 'master'
2019/01/09 13:54:08 get failed: clone failed: exit status 1
```
I've tried replicating the steps taken by this resource directly with the git client to init and pull and can do so fine with my access token without any issues, however when using the resource I just get the above. 

I was just wondering if you had any suggestions or could improve the error outputs ?

Many Thanks,

Mark Woolley

**Comment by itsdalmo** [comment]
Hey Mark! Thanks for submitting the issue!

Quick disclaimer; I don't have access to a GHE installation, so the implementation was done blindly on my part, but hopefully we can figure this out together 🙌 

It seems your error originates here:
https://github.com/telia-oss/github-pr-resource/blob/master/git.go#L81

That command basically runs:
```bash
git pull https://x-oauth-basic:<ACCESS_TOKEN>@<URI>.git <BaseRefName>
```

Since `BaseRefName` has already been used during `terraform init` the two bits of information that might give us trouble is the URI (and scheme) or the access token. Does your `access_token` have permission to read the repository? Are you using a HTTPS scheme, and if so, should you be using `skip_ssl_verification` (do you use self-signed certificates)?

**Comment by marknet15** [comment]
Hi,

That's not a problem, I don't think it's going to be a huge issue, I think it's just one of those annoying small issues, quite even possible user error on my part :)

Ok that makes sense! yes I created a fresh token with the full repo scope access, I've tested a git clone locally on my machine using the token and it succeeded. I am using the HTTPS scheme, I don't think the cert is self-signed but I will give that flag a try. 

Thanks,

Mark Woolley

**Comment by marknet15** [comment]
Hi,

So that didn't work, so i carried on testing and i found that if i launched a container instance of the github-pr resource i can manually run the ```check``` and ```in``` commands with test data and that works:
```
/ # cat testdata.json | /opt/resource/in /tmp/test
Initialized empty Git repository in /tmp/test/.git/
Switched to a new branch 'master'
Merge made by the 'recursive' strategy.
{"version":{"pr":"1","commit":"a72c45268c49edfac8836615d37529a828f64e4f","committed":"0001-01-01T00:00:00Z"},"metadata":[{"name":"pr","value":"1"},{"name":"url","value":"https://something.com/some/repo/pull/1"},{"name":"head_name","value":"mark-woolley-patch-1"},{"name":"head_sha","value":"a72c45268c49edfac8836615d37529a828f64e4f"},{"name":"base_name","value":"master"},{"name":"base_sha","value":"0f92b036e7fc3d7362813358c09fa99cf60bcf3e"},{"name":"message","value":"Create README.md"},{"name":"author","value":"mark.woolley"}]}
```

but yet it fails in Concourse! I tried the privileged flag just in case and that still failed, however the version info is definitely being passed:
![image](https://user-images.githubusercontent.com/14127638/51035653-93cbc100-15a2-11e9-85a8-c8453aeb8aa4.png)

**Comment by marknet15** [comment]
Awesome! 👍 

thanks again for your help and time!
