### ISSUE TITLE
git-crypt support

### ISSUE THREAD

**Issue by gabro** [telia-oss/github-pr-resource#67]
The official `git` resource supports decryption of a git-crypt repository via the `git_crypt_key` parameter, described as:

> `git_crypt_key`: Optional. Base64 encoded git-crypt key. Setting this will unlock / decrypt the repository with git-crypt. To get the key simply execute `git-crypt export-key -- - | base64` in an encrypted repository.

Would you be ok with supporting this same feature in this resource?

If so, I should have time to contribute a PR :)

**Comment by itsdalmo** [comment]
Hey Gabro! Sorry for the late response, but yeah I don't see any reason why the resource should not support git-crypt so it cooperates well with the `git` resource. Will happily review if you have time to do a PR 🎉

**Comment by gabro** [comment]
@itsdalmo great, thanks for the feedback! I've just sent a PR ;)
