### ISSUE TITLE
[ Feature Request ] Support for Submodules.

### ISSUE THREAD

**Issue by Typositoire** [telia-oss/github-pr-resource#69]
So I've been trying this resource to replace the one from jtarchie but I came across the fact that this doesn't do any submodule init/update. Is it something that other people want? I'm currently working to implement it but having to use HTTPS makes it a bit harder..

**Comment by itsdalmo** [comment]
Hi! Personally I don't need it, but happy to review a PR if this is something that more people want - thanks for looking into it 🙌

**Comment by Typositoire** [comment]
Submodules and HTTPS are not friends... I just ended up using a task and `alpine/git` :P

**Comment by jleben** [comment]
@Typositoire @itsdalmo I need support for submodules. HTTPS in combination with GitHub tokens works fine when using relative submodule URLs.

**Comment by astromoose** [comment]
Plus one for submodules!

**Comment by djirik** [comment]
For those who wants submodules functionality, I made a fix - [here](https://hub.docker.com/r/djirik/github-pr-resource) is my resource. Idk why my PR was not merged, but it works just fine
