### ISSUE TITLE
Run when a pull request is closed

### ISSUE THREAD

**Issue by nictrix** [telia-oss/github-pr-resource#71]
I would like to get everyone's thoughts on triggering when a PR is closed. It doesn't appear this resource can do that right now, only on commits.

Reason being when a PR is created I'd like an action to happen and when the PR is merged/closed I'd like the opposite action to happen. An example of this would be creating a review environment while the PR is open, then terminate it when the PR is merged/closed. I could always run terminate when there is a commit to master, though having multiple PRs would break that ability.

If there are other ways outside of having the `github-pr-resource` send triggers on PR actions let me know...

**Comment by shinmyung0** [comment]
I actually wrote a resource for this very problem, if you want to take a look at it.

https://github.com/shinmyung0/pullrequest-events-resource

**Comment by itsdalmo** [comment]
I think for this particular use case it makes sense to use something like what @shinmyung0 has created, since `github-pr-resource` tracks the commits within a PR and not the state of the PR itself :)

**Comment by nictrix** [comment]
@shinmyung0 awesome! Thanks for this!
@itsdalmo I'm okay with closing this issue since there is already a resource that handles it and it makes sense for it to be separate.

**Comment by shinmyung0** [comment]
@nictrix I even wrote a medium article on the process of writing it, so if you want an easy way to understand the code or even fork/contribute to it take a look:
“Writing a Custom Resource for Concourse— Detecting Pull Request Close/Merge Events” by Shin Myung Yoon https://link.medium.com/g2bI0iPkRT
