### ISSUE TITLE
Support for build metadata inside of PR comment files

### ISSUE THREAD

**Issue by shinmyung0** [telia-oss/github-pr-resource#74]
It would be nice if there could be support for some sort of template substitution for build metadata environments for the comment files. Something similar to how the slack notification resource handles this. 

https://github.com/cloudfoundry-community/slack-notification-resource#metadata

This is useful when you want to have the PR comments leave a reference to which build number or even to generate a link to the build logs directly. I know this is technically done within the status context's "details" link, but this gets easily overwritten when another commit dismisses a previous commit and there are multiple statuses.

**Comment by itsdalmo** [comment]
Hi and thanks for the issue! I think that makes a lot of sense, and I think it would be a useful addition to the resource. Happy to review a PR, or take a look at it myself in a couple of weeks when I have more time 😄

**Comment by adriagalin** [comment]
As @itsdalmo commented on https://github.com/telia-oss/github-pr-resource/pull/105#pullrequestreview-242737652, this issue could be closed.

Thank you 😄

**Comment by itsdalmo** [comment]
Yep, I'll close this one for now. It's available under the `dev` tag and will be released in the coming days (hopefully tomorrow).
