### ISSUE TITLE
Reporting back Merge Conflict to the PR

### ISSUE THREAD

**Issue by dharmesh-periscope** [telia-oss/github-pr-resource#76]
When there is a Merge Conflict in the initial `get` for a PR workflow (as shown in your Example), the PR check is left in an unknown state .

> **concourse-ci/status ** Expected — Waiting for status to be reported

What would be the best way to report a failure status back to the PR in that scenario? Thanks!

**Comment by itsdalmo** [comment]
I think using `on_failure` with `status: ERROR` for the `get` step should have you covered, since `get` will exit with a non-zero exit status if the merge fails?

**Comment by itsdalmo** [comment]
Closing this as it is stale, and I believe the proposed solution should work.
