### ISSUE TITLE
Allow for Context not to have concourse-ci Prefix in Check Name

### ISSUE THREAD

**Issue by esauser** [telia-oss/github-pr-resource#77]
We are integrated to SonarQube which decorates PRs in GitHub with the check of `SonarQube`.  This name is not configurable, so we cannot interact with this same check via the `Context` parameter because it always prefixes with `concourse-ci`.  It would be nice to be able to disable the prefix in scenarios like this.

**Comment by itsdalmo** [comment]
Makes sense to allow specifying the full context, just need to make sure we are backwards compatible if possible when fixing this.
