### ISSUE TITLE
Feature Request: Only trigger at PR to specific branches

### ISSUE THREAD

**Issue by ClumsyPotato** [telia-oss/github-pr-resource#84]
Is it possible  that a pipeline only gets triggered if the pull request contains merges into a certain branch? 
Eg: only trigger if the PR want to merge with master or only trigger if PR wants to merge into dev

**Comment by itsdalmo** [comment]
It is not currently possible with this resource, but I can see it being a useful feature to add. Happy to review a PR to implement it, or I can take a look at it myself when I have more time 🙌

**Comment by itsdalmo** [comment]
Thanks for the PR @ClumsyPotato - this is now merged and released in `v0.13.0` (image should be built and ready shortly)🎉
