### ISSUE TITLE
git-crypt increases docker image size by 50mb

### ISSUE THREAD

**Issue by itsdalmo** [telia-oss/github-pr-resource#87]
According to docker hub, the latest `dev` [tags](https://cloud.docker.com/u/teliaoss/repository/docker/teliaoss/github-pr-resource/tags) have increased from 24 to 76mb after the addition of `git-crypt` in the image. In an effort to keep the image lightweight, I'm wondering if perhaps it is possible to trim it down a bit.

If that is not possible, I wonder if perhaps we could build `git-crypt` in a separate image and include a `task.yml` in this repository which can be used for the decrypting - to avoid inflating the image for all the people that _don't_ have encrypted repos?

Thoughts @gabro?

**Comment by gabro** [comment]
Hi @itsdalmo sorry for the late reply.

The size increase seems a bit high, could it be that `apk remove` doesn't remove the cache? We might want try to `rm -rf /var/cache/apk/*` and see whether that brings the size down to a more reasonable number.

If that doesn't help, I'm open to exploring different solutions to the approach, including having an alternative tag git-crypt support.

**Comment by gabro** [comment]
Hi @itsdalmo, good news! Properly removing the build dependencies seems to fix it: https://github.com/telia-oss/github-pr-resource/pull/92

**Comment by itsdalmo** [comment]
Reopening this so we remember to verify that `git-crypt` actually works. Current `dev` image is only 2mb larger than the last release 🎉

**Comment by itsdalmo** [comment]
@gabro - Have you had a chance to test the `git-crypt` support currently on the `dev` branch? If so we can make a release, but I'd really like some confirmation that it actually works for you 😅

**Comment by gabro** [comment]
@itsdalmo just tested it and it works 🎉 

I've also tested it with a dummy public pipeline https://concourse.our.buildo.io/teams/buildo/pipelines/git-crypt and it works there too.

**Comment by itsdalmo** [comment]
Thank you for reporting back 🙌 Will close this issue and create a new release!
