### ISSUE TITLE
README is potentially misleading about webhook configuration

### ISSUE THREAD

**Issue by mdb** [telia-oss/github-pr-resource#91]
According to `github-pr-resource`'s `README`, the webhook "should be subscribed to `push` events." However, it's my tentative belief that [push](https://developer.github.com/v3/activity/events/types/#pushevent) events alone will not trigger the webhook when a PR is opened. This can lead to scenarios where Concourse CI jobs validating pull requests are not triggered when a pull request is opened. I believe the documentation should advise that users configure their webhooks to subscribe to both pull request events and push events. Am I confused or mistaken?

If I'm correct, I'm happy to submit a pull request improving the documentation; just wanted a sanity check before I do. Thanks!

Here are my steps to reproduce, given a `my-code` pipeline containing a `my-code-pr` resource and a `validate-my-code-pr` job as represented in [this pipeline](https://gist.github.com/mdb/0f9fd69776cb093f397016095ef254bc)...

1. configure a GitHub webhook for `https://my-concourse.com/api/v1/teams/my-team/pipelines/my-code/resources/my-code-pr/check/webhook?webhook_token=123`. For "Which events would you like to trigger this webhook?," choose "Just the push event."

2. push a branch to the the `my-code` repo (note that _this_ action _will_ trigger the webhook and a subsequent Concourse check for `my-code-pr` versions, though at this point no new PRs have been created)

3. Open a pull request. Note that no webhook is triggered and thus no subsequent Concourse check for `my-code-pr` versions is performed and the `validate-my-code-pr` job does not run, despite `trigger: true`.

**Comment by itsdalmo** [comment]
I just had a look at the webhooks created by both Travis and Dockerhub for this repository, and they both subscribe to the `Push` _and_ `PullRequestEvent` - so without testing this, I believe you are correct! Will make a note of it in the documentation 😅

**Comment by itsdalmo** [comment]
Fixed! Thanks for reporting 🙌

**Comment by mdb** [comment]
@itsdalmo Thanks so much! (And sorry the issue wasn't accompanied by a PR from me; I wanted a sanity check before creating the PR)
