### ISSUE TITLE
[feature request] Option to rebase instead of merge

### ISSUE THREAD

**Issue by aryzing** [telia-oss/github-pr-resource#96]
Currently, the tool will attempt to merge `master` with the branch in the PR. Could you add an option to rebase instead? Our git flow relies on rebasing onto master, so performing a rebase interferes with some of the checks we do.

**Comment by itsdalmo** [comment]
Implemented in #97 - lets try out the `dev` image and confirm that it is working, add tests and get this released.

**Comment by itsdalmo** [comment]
Tests have been added, so if `rebase` is working as expected in the current `dev` image I think we are good to go with a release here?

**Comment by aryzing** [comment]
Glad you added the tests :) Rebase is working as expected on my end, significantly cutting down or CI time.

Regarding the change in location of the `integration_tool` parameter, it makes sense to have it closer to where it's being used :+1:

**Comment by itsdalmo** [comment]
The PR linked above has been merged now, so `integration_tool` is a parameter for `get` instead of being a part of the `source` config. Check out the `dev` image and let me know how it works for you 👍

**Comment by itsdalmo** [comment]
Just fixed the automated build for docker hub, so `dev` was _just_ updated.

**Comment by aryzing** [comment]
Thanks for all the updates, might need to wait until next week to check, I'll let you know

**Comment by itsdalmo** [comment]
Closing this as it seems to work fine 😅
